language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: pNPPlZBrz7PUdpJdpfKdSPoekpR84+t6RKMSwe2h0pBJDCX6CNxjnzhnGhCa2oD2DFMDQYrE59yFjlMNxruHvaXvdbwr2+HPx0o9fiKI1cT24ikFJoebCyBtt5vk/qH9KTAASh3FpPw9s1+5tYWy6IA968Wr4RdJbHTHcxQ0/rXGvh5rVO/BvEnPWGZjfRLV22xPaqgN/GBMkTLyIpRQzexN2tyARF7fXZf6x6NDjQ4MX64gz8z6Goww5IGcmZi5hrsmUeIvJhJ9Ba/snwHwn+IJ0qhe3C78fF5HrxF/0cMTbQteD1ULqJHy45rNcQ6YjDt0xKFibcx2S1uK4r8H9pX0wx3Wa56qX3fJ0JMwoeFuXc0B/bkZ53QJEPcwPXnVhi1SOM/DLgsK3raYdJRt4BMU7Xo3KK77aDIZY+O28IplfBgA0KGSfEcLCfw1BvhZoYKUuLRaNHuM857GzaetIWAYhCvEn9whfsP/0ye9uPt/vSoHjzMcJKJz36kmD61lPwymk/rwv0OBRyrXEHFyrwppcLel03P3vBQm0WAed3cwXUsTUCxHeI7bC1KwgTLXk6Jj8tS+nJckRSFlBcjyHhRaSXZ8eRVUABZslt24pHPHiBBDJ9Ax3BWXbB5ZIda/1i1BfyxnlbdM2A4nCg6DLvSZEH7VyeJi30E3XtRaYSU=
